# Generated by Django 5.2.3 on 2025-06-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(4, '4-Seater'), (6, '6-Seater'), (8, '8-Seater')], unique=True)),
                ('available_tables', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tablecategory')),
            ],
        ),
    ]
